EVENT(mouse, Component, parent)
EVENT(left, Component, parent)
EVENT(right, Component, parent)
EVENT(middle, Component, parent)
EVENT(touches, List, parent)
EVENT2(stylus_pen, FatSpike, parent, pen)
EVENT2(stylus_eraser, FatSpike, parent, eraser)
