namespace djnn
{
#ifndef DJNN_NO_DEBUG // still required to link smala programs
  // DEBUG OPTIONS
    int
    _DEBUG_SEE_COLOR_PICKING_VIEW=0,
    _DEBUG_GRAPH_CYCLE_DETECT=0,
    _DEBUG_SEE_ACTIVATION_SEQUENCE=0,
    _DEBUG_SEE_ACTIVATION_SEQUENCE_TARGET_TIME_US=1000,
    _DEBUG_SEE_ACTIVATION_SEQUENCE_ONLY_TARGETED=1
    ;
#endif
}