/*
 *  djnn v2
 *
 *  The copyright holders for the contents of this file are:
 *      Ecole Nationale de l'Aviation Civile, France (2019)
 *  See file "license.terms" for the rights and conditions
 *  defined by copyright holders.
 *
 *
 *  Contributors:
 *      Mathieu Magnaudet <mathieu.magnaudet@enac.fr>
 *
 */

MACRO (Tab)
MACRO (Backtab)
MACRO (Backspace)
MACRO (Return)
MACRO (Enter)
MACRO (Insert)
MACRO (Delete)
MACRO (Pause)
MACRO (Print)
MACRO (SysReq)
MACRO (Clear)
MACRO (Home)
MACRO (End)
MACRO (Left)
MACRO (Up)
MACRO (Right)
MACRO (Down)
MACRO (PageUp)
MACRO (PageDown)
MACRO (Shift)
MACRO (Control)
MACRO (Meta)
MACRO (Alt)
MACRO (AltGr)
MACRO (CapsLock)
MACRO (NumLock)
MACRO (ScrollLock)
MACRO (F1)
MACRO (F2)
MACRO (F3)
MACRO (F4)
MACRO (F5)
MACRO (F6)
MACRO (F7)
MACRO (F8)
MACRO (F9)
MACRO (F10)
MACRO (F11)
MACRO (F12)
MACRO (F13)
MACRO (F14)
MACRO (F15)
MACRO (F16)
MACRO (F17)
MACRO (F18)
MACRO (F19)
MACRO (F20)
MACRO (F21)
MACRO (F22)
MACRO (F23)
MACRO (F24)
MACRO (F25)
MACRO (F26)
MACRO (F27)
MACRO (F28)
MACRO (F29)
MACRO (F30)
MACRO (F31)
MACRO (F32)
MACRO (F33)
MACRO (F34)
MACRO (F35)
MACRO (Super_L)
MACRO (Super_R)
MACRO (Menu)
MACRO (Hyper_L)
MACRO (Hyper_R)
MACRO (Help)
MACRO (Direction_L)
MACRO (Direction_R)
MACRO (Space)
MACRO (Any)
MACRO (Exclam)
MACRO (QuoteDbl)
MACRO (NumberSign)
MACRO (Dollar)
MACRO (Percent)
MACRO (Ampersand)
MACRO (Apostrophe)
MACRO (ParenLeft)
MACRO (ParenRight)
MACRO (Asterisk)
MACRO (Plus)
MACRO (Comma)
MACRO (Minus)
MACRO (Period)
MACRO (Slash)
MACRO(0)
MACRO(1)
MACRO(2)
MACRO(3)
MACRO(4)
MACRO(5)
MACRO(6)
MACRO(7)
MACRO(8)
MACRO(9)
MACRO(Colon)
MACRO(Semicolon)
MACRO(Less)
MACRO(Equal)
MACRO(Greater)
MACRO(Question)
MACRO(At)
MACRO(A)
MACRO(B)
MACRO(C)
MACRO(D)
MACRO(E)
MACRO(F)
MACRO(G)
MACRO(H)
MACRO(I)
MACRO(J)
MACRO(K)
MACRO(L)
MACRO(M)
MACRO(N)
MACRO(O)
MACRO(P)
MACRO(Q)
MACRO(R)
MACRO(S)
MACRO(T)
MACRO(U)
MACRO(V)
MACRO(W)
MACRO(X)
MACRO(Y)
MACRO(Z)
MACRO(BracketLeft)
MACRO(Backslash)
MACRO(BracketRight)
MACRO(AsciiCircum)
MACRO(Underscore)
MACRO(QuoteLeft)
MACRO(BraceLeft)
MACRO(Bar)
MACRO(BraceRight)
MACRO(AsciiTilde)
MACRO(nobreakspace)
MACRO(exclamdown)
MACRO(cent)
MACRO(sterling)
MACRO(currency)
MACRO(yen)
MACRO(brokenbar)
MACRO(section)
MACRO(diaeresis)
MACRO(copyright)
MACRO(ordfeminine)
MACRO(guillemotleft)
MACRO(notsign)
MACRO(hyphen)
MACRO(registered)
MACRO(macron)
MACRO(degree)
MACRO(plusminus)
MACRO(twosuperior)
MACRO(threesuperior)
MACRO(acute)
MACRO(mu)
MACRO(paragraph)
MACRO(periodcentered)
MACRO(cedilla)
MACRO(onesuperior)
MACRO(masculine)
MACRO(guillemotright)
MACRO(onequarter)
MACRO(onehalf)
MACRO(threequarters)
MACRO(questiondown)
MACRO(Agrave)
MACRO(Aacute)
MACRO(Acircumflex)
MACRO(Atilde)
MACRO(Adiaeresis)
MACRO(Aring)
MACRO(AE)
MACRO(Ccedilla)
MACRO(Egrave)
MACRO(Eacute)
MACRO(Ecircumflex)
MACRO(Ediaeresis)
MACRO(Igrave)
MACRO(Iacute)
MACRO(Icircumflex)
MACRO(Idiaeresis)
MACRO(ETH)
MACRO(Ntilde)
MACRO(Ograve)
MACRO(Oacute)
MACRO(Ocircumflex)
MACRO(Otilde)
MACRO(Odiaeresis)
MACRO(multiply)
MACRO(Ooblique)
MACRO(Ugrave)
MACRO(Uacute)
MACRO(Ucircumflex)
MACRO(Udiaeresis)
MACRO(Yacute)
MACRO(THORN)
MACRO(ssharp)
MACRO(division)
MACRO(ydiaeresis)
MACRO(Multi_key)
MACRO(Codeinput)
MACRO(SingleCandidate)
MACRO(MultipleCandidate)
MACRO(PreviousCandidate)
MACRO(Mode_switch)
MACRO(Kanji)
MACRO(Muhenkan)
MACRO(Henkan)
MACRO(Romaji)
MACRO(Hiragana)
MACRO(Katakana)
MACRO(Hiragana_Katakana)
MACRO(Zenkaku)
MACRO(Hankaku)
MACRO(Zenkaku_Hankaku)
MACRO(Touroku)
MACRO(Massyo)
MACRO(Kana_Lock)
MACRO(Kana_Shift)
MACRO(Eisu_Shift)
MACRO(Eisu_toggle)
MACRO(Hangul)
MACRO(Hangul_Start)
MACRO(Hangul_End)
MACRO(Hangul_Hanja)
MACRO(Hangul_Jamo)
MACRO(Hangul_Romaja)
MACRO(Hangul_Jeonja)
MACRO(Hangul_Banja)
MACRO(Hangul_PreHanja)
MACRO(Hangul_PostHanja)
MACRO(Hangul_Special)
MACRO(Dead_Grave)
MACRO(Dead_Acute)
MACRO(Dead_Circumflex)
MACRO(Dead_Tilde)
MACRO(Dead_Macron)
MACRO(Dead_Breve)
MACRO(Dead_Abovedot)
MACRO(Dead_Diaeresis)
MACRO(Dead_Abovering)
MACRO(Dead_Doubleacute)
MACRO(Dead_Caron)
MACRO(Dead_Cedilla)
MACRO(Dead_Ogonek)
MACRO(Dead_Iota)
MACRO(Dead_Voiced_Sound)
MACRO(Dead_Semivoiced_Sound)
MACRO(Dead_Belowdot)
MACRO(Dead_Hook)
MACRO(Dead_Horn)
MACRO(Dead_Stroke)
MACRO(Dead_Abovecomma)
MACRO(Dead_Abovereversedcomma)
MACRO(Dead_Doublegrave)
MACRO(Dead_Belowring)
MACRO(Dead_Belowmacron)
MACRO(Dead_Belowcircumflex)
MACRO(Dead_Belowtilde)
MACRO(Dead_Belowbreve)
MACRO(Dead_Belowdiaeresis)
MACRO(Dead_Invertedbreve)
MACRO(Dead_Belowcomma)
MACRO(Dead_Currency)
MACRO(Dead_a)
MACRO(Dead_A)
MACRO(Dead_e)
MACRO(Dead_E)
MACRO(Dead_i)
MACRO(Dead_I)
MACRO(Dead_o)
MACRO(Dead_O)
MACRO(Dead_u)
MACRO(Dead_U)
MACRO(Dead_Small_Schwa)
MACRO(Dead_Capital_Schwa)
MACRO(Dead_Greek)
MACRO(Dead_Lowline)
MACRO(Dead_Aboveverticalline)
MACRO(Dead_Belowverticalline)
MACRO(Dead_Longsolidusoverlay)
MACRO(Back)
MACRO(Forward)
MACRO(Stop)
MACRO(Refresh)
MACRO(VolumeDown)
MACRO(VolumeMute)
MACRO(VolumeUp)
MACRO(BassBoost)
MACRO(BassUp)
MACRO(BassDown)
MACRO(TrebleUp)
MACRO(TrebleDown)
MACRO(MediaPlay)
MACRO(MediaStop)
MACRO(MediaPrevious)
MACRO(MediaNext)
MACRO(MediaRecord)
MACRO(MediaPause)
MACRO(MediaTogglePlayPause)
MACRO(HomePage)
MACRO(Favorites)
MACRO(Search)
MACRO(Standby)
MACRO(OpenUrl)
MACRO(LaunchMail)
MACRO(LaunchMedia)
MACRO(Launch0)
MACRO(Launch1)
MACRO(Launch2)
MACRO(Launch3)
MACRO(Launch4)
MACRO(Launch5)
MACRO(Launch6)
MACRO(Launch7)
MACRO(Launch8)
MACRO(Launch9)
MACRO(LaunchA)
MACRO(LaunchB)
MACRO(LaunchC)
MACRO(LaunchD)
MACRO(LaunchE)
MACRO(LaunchF)
MACRO(LaunchG)
MACRO(LaunchH)
MACRO(MonBrightnessUp)
MACRO(MonBrightnessDown)
MACRO(KeyboardLightOnOff)
MACRO(KeyboardBrightnessUp)
MACRO(KeyboardBrightnessDown)
MACRO(PowerOff)
MACRO(WakeUp)
MACRO(Eject)
MACRO(ScreenSaver)
MACRO(WWW)
MACRO(Memo)
MACRO(LightBulb)
MACRO(Shop)
MACRO(History)
MACRO(AddFavorite)
MACRO(HotLinks)
MACRO(BrightnessAdjust)
MACRO(Finance)
MACRO(Community)
MACRO(AudioRewind)
MACRO(BackForward)
MACRO(ApplicationLeft)
MACRO(ApplicationRight)
MACRO(Book)
MACRO(CD)
MACRO(Calculator)
MACRO(ToDoList)
MACRO(ClearGrab)
MACRO(Close)
MACRO(Copy)
MACRO(Cut)
MACRO(Display)
MACRO(DOS)
MACRO(Documents)
MACRO(Excel)
MACRO(Explorer)
MACRO(Game)
MACRO(Go)
MACRO(iTouch)
MACRO(LogOff)
MACRO(Market)
MACRO(Meeting)
MACRO(MenuKB)
MACRO(MenuPB)
MACRO(MySites)
MACRO(News)
MACRO(OfficeHome)
MACRO(Option)
MACRO(Paste)
MACRO(Phone)
MACRO(Calendar)
MACRO(Reply)
MACRO(Reload)
MACRO(RotateWindows)
MACRO(RotationPB)
MACRO(RotationKB)
MACRO(Save)
MACRO(Send)
MACRO(Spell)
MACRO(SplitScreen)
MACRO(Support)
MACRO(TaskPane)
MACRO(Terminal)
MACRO(Tools)
MACRO(Travel)
MACRO(Video)
MACRO(Word)
MACRO(Xfer)
MACRO(ZoomIn)
MACRO(ZoomOut)
MACRO(Away)
MACRO(Messenger)
MACRO(WebCam)
MACRO(MailForward)
MACRO(Pictures)
MACRO(Music)
MACRO(Battery)
MACRO(Bluetooth)
MACRO(WLAN)
MACRO(UWB)
MACRO(AudioForward)
MACRO(AudioRepeat)
MACRO(AudioRandomPlay)
MACRO(Subtitle)
MACRO(AudioCycleTrack)
MACRO(Time)
MACRO(Hibernate)
MACRO(View)
MACRO(TopMenu)
MACRO(PowerDown)
MACRO(Suspend)
MACRO(ContrastAdjust)
MACRO(TouchpadToggle)
MACRO(TouchpadOn)
MACRO(TouchpadOff)
MACRO(MicMute)
MACRO(Red)
MACRO(Green)
MACRO(Yellow)
MACRO(Blue)
MACRO(ChannelUp)
MACRO(ChannelDown)
MACRO(Guide)
MACRO(Info)
MACRO(Settings)
MACRO(MicVolumeUp)
MACRO(MicVolumeDown)
MACRO(New)
MACRO(Open)
MACRO(Find)
MACRO(Undo)
MACRO(Redo)
MACRO(MediaLast)
MACRO(unknown)
MACRO(Call)
MACRO(Camera)
MACRO(CameraFocus)
MACRO(Context1)
MACRO(Context2)
MACRO(Context3)
MACRO(Context4)
MACRO(Flip)
MACRO(Hangup)
MACRO(No)
MACRO(Select)
MACRO(Yes)
MACRO(ToggleCallHangup)
MACRO(VoiceDial)
MACRO(LastNumberRedial)
MACRO(Execute)
MACRO(Printer)
MACRO(Play)
MACRO(Sleep)
MACRO(Zoom)
MACRO(Exit)
MACRO(Cancel)
