/*
 *  djnn v2
 *
 *  The copyright holders for the contents of this file are:
 *      Ecole Nationale de l'Aviation Civile, France (2019)
 *  See file "license.terms" for the rights and conditions
 *  defined by copyright holders.
 *
 *
 *  Contributors:
 *      Stephane Conversy <stephane.conversy@enac.fr>
 *      Mathieu Magnaudet <mathieu.magnaudet@enac.fr>
 *
 */

MACRO (Tab, TAB)
// MACRO (Backtab, BACKTAB)
MACRO (Backspace, BACKSPACE)
MACRO (Return, RETURN)
// MACRO (Enter, ENTER)
MACRO (Insert, INSERT)
MACRO (Delete, DELETE)
MACRO (Pause, PAUSE)
// MACRO (Print, PRINT)
MACRO (SysReq, SYSREQ)
MACRO (Clear, CLEAR)
MACRO (Home, HOME)
MACRO (End, END)
MACRO (Left, LEFT)
MACRO (Up, UP)
MACRO (Right, RIGHT)
MACRO (Down, DOWN)
MACRO (PageUp, PAGEUP)
MACRO (PageDown, PAGEDOWN)
// MACRO (Shift, SHIFT)
// MACRO (Control, CONTROL)
// MACRO (Meta, META)
// MACRO (Alt, ALT)
// MACRO (AltGr, ALTGR)
MACRO (CapsLock, CAPSLOCK)
// MACRO (NumLock, NUMLOCK)
MACRO (ScrollLock, SCROLLLOCK)
MACRO (F1, F1)
MACRO (F2, F2)
MACRO (F3, F3)
MACRO (F4, F4)
MACRO (F5, F5)
MACRO (F6, F6)
MACRO (F7, F7)
MACRO (F8, F8)
MACRO (F9, F9)
MACRO (F10, F10)
MACRO (F11, F11)
MACRO (F12, F12)
MACRO (F13, F13)
MACRO (F14, F14)
MACRO (F15, F15)
MACRO (F16, F16)
MACRO (F17, F17)
MACRO (F18, F18)
MACRO (F19, F19)
MACRO (F20, F20)
MACRO (F21, F21)
MACRO (F22, F22)
MACRO (F23, F23)
MACRO (F24, F24)
// MACRO (Super_L, SUPER_L)
// MACRO (Super_R, SUPER_R)
MACRO (Menu, MENU)
// MACRO (Hyper_L, HYPER_L)
// MACRO (Hyper_R, HYPER_R)
MACRO (Help, HELP)
// MACRO (Direction_L, DIRECTION_L)
// MACRO (Direction_R, DIRECTION_R)
MACRO (Space, SPACE)
// MACRO (Any, ANY)
// MACRO (Exclam, EXCLAM)
MACRO (QuoteDbl, QUOTEDBL)
// MACRO (NumberSign, NUMBERSIGN)
MACRO (Dollar, DOLLAR)
MACRO (Percent, PERCENT)
MACRO (Ampersand, AMPERSAND)
// MACRO (Apostrophe, APOSTROPHE)
// MACRO (ParenLeft, PARENLEFT)
// MACRO (ParenRight, PARENRIGHT)
MACRO (Asterisk, ASTERISK)
MACRO (Plus, PLUS)
MACRO (Comma, COMMA)
MACRO (Minus, MINUS)
MACRO (Period, PERIOD)
MACRO (Slash, SLASH)
MACRO (0, 0)
MACRO (1, 1)
MACRO (2, 2)
MACRO (3, 3)
MACRO (4, 4)
MACRO (5, 5)
MACRO (6, 6)
MACRO (7, 7)
MACRO (8, 8)
MACRO (9, 9)
MACRO (Colon, COLON)
MACRO (Semicolon, SEMICOLON)
MACRO (Less, LESS)
// MACRO (Equal, EQUAL)
MACRO (Greater, GREATER)
MACRO (Question, QUESTION)
MACRO (At, AT)
MACRO (A, A)
MACRO (B, B)
MACRO (C, C)
MACRO (D, D)
MACRO (E, E)
MACRO (F, F)
MACRO (G, G)
MACRO (H, H)
MACRO (I, I)
MACRO (J, J)
MACRO (K, K)
MACRO (L, L)
MACRO (M, M)
MACRO (N, N)
MACRO (O, O)
MACRO (P, P)
MACRO (Q, Q)
MACRO (R, R)
MACRO (S, S)
MACRO (T, T)
MACRO (U, U)
MACRO (V, V)
MACRO (W, W)
MACRO (X, X)
MACRO (Y, Y)
MACRO (Z, Z)
// MACRO (BracketLeft, BRACKETLEFT)
MACRO (Backslash, BACKSLASH)
// MACRO (BracketRight, BRACKETRIGHT)
// MACRO (AsciiCircum, ASCIICIRCUM)
// MACRO (Underscore, UNDERSCORE)
// MACRO (QuoteLeft, QUOTELEFT)
// MACRO (BraceLeft, BRACELEFT)
// MACRO (Bar, BAR)
// MACRO (BraceRight, BRACERIGHT)
// MACRO (AsciiTilde, ASCIITILDE)
// MACRO (nobreakspace, NOBREAKSPACE)
// MACRO (exclamdown, EXCLAMDOWN)
// MACRO (cent, CENT)
// MACRO (sterling, STERLING)
// MACRO (currency, CURRENCY)
// MACRO (yen, YEN)
// MACRO (brokenbar, BROKENBAR)
// MACRO (section, SECTION)
// MACRO (diaeresis, DIAERESIS)
// MACRO (copyright, COPYRIGHT)
// MACRO (ordfeminine, ORDFEMININE)
// MACRO (guillemotleft, GUILLEMOTLEFT)
// MACRO (notsign, NOTSIGN)
// MACRO (hyphen, HYPHEN)
// MACRO (registered, REGISTERED)
// MACRO (macron, MACRON)
// MACRO (degree, DEGREE)
// MACRO (plusminus, PLUSMINUS)
// MACRO (twosuperior, TWOSUPERIOR)
// MACRO (threesuperior, THREESUPERIOR)
// MACRO (acute, ACUTE)
// MACRO (mu, MU)
// MACRO (paragraph, PARAGRAPH)
// MACRO (periodcentered, PERIODCENTERED)
// MACRO (cedilla, CEDILLA)
// MACRO (onesuperior, ONESUPERIOR)
// MACRO (masculine, MASCULINE)
// MACRO (guillemotright, GUILLEMOTRIGHT)
// MACRO (onequarter, ONEQUARTER)
// MACRO (onehalf, ONEHALF)
// MACRO (threequarters, THREEQUARTERS)
// MACRO (questiondown, QUESTIONDOWN)
// MACRO (Agrave, AGRAVE)
// MACRO (Aacute, AACUTE)
// MACRO (Acircumflex, ACIRCUMFLEX)
// MACRO (Atilde, ATILDE)
// MACRO (Adiaeresis, ADIAERESIS)
// MACRO (Aring, ARING)
// MACRO (AE, AE)
// MACRO (Ccedilla, CCEDILLA)
// MACRO (Egrave, EGRAVE)
// MACRO (Eacute, EACUTE)
// MACRO (Ecircumflex, ECIRCUMFLEX)
// MACRO (Ediaeresis, EDIAERESIS)
// MACRO (Igrave, IGRAVE)
// MACRO (Iacute, IACUTE)
// MACRO (Icircumflex, ICIRCUMFLEX)
// MACRO (Idiaeresis, IDIAERESIS)
// MACRO (ETH, ETH)
// MACRO (Ntilde, NTILDE)
// MACRO (Ograve, OGRAVE)
// MACRO (Oacute, OACUTE)
// MACRO (Ocircumflex, OCIRCUMFLEX)
// MACRO (Otilde, OTILDE)
// MACRO (Odiaeresis, ODIAERESIS)
// MACRO (multiply, MULTIPLY)
// MACRO (Ooblique, OOBLIQUE)
// MACRO (Ugrave, UGRAVE)
// MACRO (Uacute, UACUTE)
// MACRO (Ucircumflex, UCIRCUMFLEX)
// MACRO (Udiaeresis, UDIAERESIS)
// MACRO (Yacute, YACUTE)
// MACRO (THORN, THORN)
// MACRO (ssharp, SSHARP)
// MACRO (division, DIVISION)
// MACRO (ydiaeresis, YDIAERESIS)
// MACRO (Multi_key, MULTI_KEY)
// MACRO (Codeinput, CODEINPUT)
// MACRO (SingleCandidate, SINGLECANDIDATE)
// MACRO (MultipleCandidate, MULTIPLECANDIDATE)
// MACRO (PreviousCandidate, PREVIOUSCANDIDATE)
// MACRO (Mode_switch, MODE_SWITCH)
// MACRO (Kanji, KANJI)
// MACRO (Muhenkan, MUHENKAN)
// MACRO (Henkan, HENKAN)
// MACRO (Romaji, ROMAJI)
// MACRO (Hiragana, HIRAGANA)
// MACRO (Katakana, KATAKANA)
// MACRO (Hiragana_Katakana, HIRAGANA_KATAKANA)
// MACRO (Zenkaku, ZENKAKU)
// MACRO (Hankaku, HANKAKU)
// MACRO (Zenkaku_Hankaku, ZENKAKU_HANKAKU)
// MACRO (Touroku, TOUROKU)
// MACRO (Massyo, MASSYO)
// MACRO (Kana_Lock, KANA_LOCK)
// MACRO (Kana_Shift, KANA_SHIFT)
// MACRO (Eisu_Shift, EISU_SHIFT)
// MACRO (Eisu_toggle, EISU_TOGGLE)
// MACRO (Hangul, HANGUL)
// MACRO (Hangul_Start, HANGUL_START)
// MACRO (Hangul_End, HANGUL_END)
// MACRO (Hangul_Hanja, HANGUL_HANJA)
// MACRO (Hangul_Jamo, HANGUL_JAMO)
// MACRO (Hangul_Romaja, HANGUL_ROMAJA)
// MACRO (Hangul_Jeonja, HANGUL_JEONJA)
// MACRO (Hangul_Banja, HANGUL_BANJA)
// MACRO (Hangul_PreHanja, HANGUL_PREHANJA)
// MACRO (Hangul_PostHanja, HANGUL_POSTHANJA)
// MACRO (Hangul_Special, HANGUL_SPECIAL)
// MACRO (Dead_Grave, DEAD_GRAVE)
// MACRO (Dead_Acute, DEAD_ACUTE)
// MACRO (Dead_Circumflex, DEAD_CIRCUMFLEX)
// MACRO (Dead_Tilde, DEAD_TILDE)
// MACRO (Dead_Macron, DEAD_MACRON)
// MACRO (Dead_Breve, DEAD_BREVE)
// MACRO (Dead_Abovedot, DEAD_ABOVEDOT)
// MACRO (Dead_Diaeresis, DEAD_DIAERESIS)
// MACRO (Dead_Abovering, DEAD_ABOVERING)
// MACRO (Dead_Doubleacute, DEAD_DOUBLEACUTE)
// MACRO (Dead_Caron, DEAD_CARON)
// MACRO (Dead_Cedilla, DEAD_CEDILLA)
// MACRO (Dead_Ogonek, DEAD_OGONEK)
// MACRO (Dead_Iota, DEAD_IOTA)
// MACRO (Dead_Voiced_Sound, DEAD_VOICED_SOUND)
// MACRO (Dead_Semivoiced_Sound, DEAD_SEMIVOICED_SOUND)
// MACRO (Dead_Belowdot, DEAD_BELOWDOT)
// MACRO (Dead_Hook, DEAD_HOOK)
// MACRO (Dead_Horn, DEAD_HORN)
// MACRO (Dead_Stroke, DEAD_STROKE)
// MACRO (Dead_Abovecomma, DEAD_ABOVECOMMA)
// MACRO (Dead_Abovereversedcomma, DEAD_ABOVEREVERSEDCOMMA)
// MACRO (Dead_Doublegrave, DEAD_DOUBLEGRAVE)
// MACRO (Dead_Belowring, DEAD_BELOWRING)
// MACRO (Dead_Belowmacron, DEAD_BELOWMACRON)
// MACRO (Dead_Belowcircumflex, DEAD_BELOWCIRCUMFLEX)
// MACRO (Dead_Belowtilde, DEAD_BELOWTILDE)
// MACRO (Dead_Belowbreve, DEAD_BELOWBREVE)
// MACRO (Dead_Belowdiaeresis, DEAD_BELOWDIAERESIS)
// MACRO (Dead_Invertedbreve, DEAD_INVERTEDBREVE)
// MACRO (Dead_Belowcomma, DEAD_BELOWCOMMA)
// MACRO (Dead_Currency, DEAD_CURRENCY)
// MACRO (Dead_a, DEAD_A)
// MACRO (Dead_A, DEAD_A)
// MACRO (Dead_e, DEAD_E)
// MACRO (Dead_E, DEAD_E)
// MACRO (Dead_i, DEAD_I)
// MACRO (Dead_I, DEAD_I)
// MACRO (Dead_o, DEAD_O)
// MACRO (Dead_O, DEAD_O)
// MACRO (Dead_u, DEAD_U)
// MACRO (Dead_U, DEAD_U)
// MACRO (Dead_Small_Schwa, DEAD_SMALL_SCHWA)
// MACRO (Dead_Capital_Schwa, DEAD_CAPITAL_SCHWA)
// MACRO (Dead_Greek, DEAD_GREEK)
// MACRO (Dead_Lowline, DEAD_LOWLINE)
// MACRO (Dead_Aboveverticalline, DEAD_ABOVEVERTICALLINE)
// MACRO (Dead_Belowverticalline, DEAD_BELOWVERTICALLINE)
// MACRO (Dead_Longsolidusoverlay, DEAD_LONGSOLIDUSOVERLAY)
// MACRO (Back, BACK)
// MACRO (Forward, FORWARD)
// MACRO (Stop, STOP)
// MACRO (Refresh, REFRESH)
// MACRO (VolumeDown, VOLUMEDOWN)
// MACRO (VolumeMute, VOLUMEMUTE)
// MACRO (VolumeUp, VOLUMEUP)
// MACRO (BassBoost, BASSBOOST)
// MACRO (BassUp, BASSUP)
// MACRO (BassDown, BASSDOWN)
// MACRO (TrebleUp, TREBLEUP)
// MACRO (TrebleDown, TREBLEDOWN)
// MACRO (MediaPlay, MEDIAPLAY)
// MACRO (MediaStop, MEDIASTOP)
// MACRO (MediaPrevious, MEDIAPREVIOUS)
// MACRO (MediaNext, MEDIANEXT)
// MACRO (MediaRecord, MEDIARECORD)
// MACRO (MediaPause, MEDIAPAUSE)
// MACRO (MediaTogglePlayPause, MEDIATOGGLEPLAYPAUSE)
// MACRO (HomePage, HOMEPAGE)
// MACRO (Favorites, FAVORITES)
// MACRO (Search, SEARCH)
// MACRO (Standby, STANDBY)
// MACRO (OpenUrl, OPENURL)
// MACRO (LaunchMail, LAUNCHMAIL)
// MACRO (LaunchMedia, LAUNCHMEDIA)
// MACRO (Launch0, LAUNCH0)
// MACRO (Launch1, LAUNCH1)
// MACRO (Launch2, LAUNCH2)
// MACRO (Launch3, LAUNCH3)
// MACRO (Launch4, LAUNCH4)
// MACRO (Launch5, LAUNCH5)
// MACRO (Launch6, LAUNCH6)
// MACRO (Launch7, LAUNCH7)
// MACRO (Launch8, LAUNCH8)
// MACRO (Launch9, LAUNCH9)
// MACRO (LaunchA, LAUNCHA)
// MACRO (LaunchB, LAUNCHB)
// MACRO (LaunchC, LAUNCHC)
// MACRO (LaunchD, LAUNCHD)
// MACRO (LaunchE, LAUNCHE)
// MACRO (LaunchF, LAUNCHF)
// MACRO (LaunchG, LAUNCHG)
// MACRO (LaunchH, LAUNCHH)
// MACRO (MonBrightnessUp, MONBRIGHTNESSUP)
// MACRO (MonBrightnessDown, MONBRIGHTNESSDOWN)
// MACRO (KeyboardLightOnOff, KEYBOARDLIGHTONOFF)
// MACRO (KeyboardBrightnessUp, KEYBOARDBRIGHTNESSUP)
// MACRO (KeyboardBrightnessDown, KEYBOARDBRIGHTNESSDOWN)
// MACRO (PowerOff, POWEROFF)
// MACRO (WakeUp, WAKEUP)
// MACRO (Eject, EJECT)
// MACRO (ScreenSaver, SCREENSAVER)
// MACRO (WWW, WWW)
// MACRO (Memo, MEMO)
// MACRO (LightBulb, LIGHTBULB)
// MACRO (Shop, SHOP)
// MACRO (History, HISTORY)
// MACRO (AddFavorite, ADDFAVORITE)
// MACRO (HotLinks, HOTLINKS)
// MACRO (BrightnessAdjust, BRIGHTNESSADJUST)
// MACRO (Finance, FINANCE)
// MACRO (Community, COMMUNITY)
// MACRO (AudioRewind, AUDIOREWIND)
// MACRO (BackForward, BACKFORWARD)
// MACRO (ApplicationLeft, APPLICATIONLEFT)
// MACRO (ApplicationRight, APPLICATIONRIGHT)
// MACRO (Book, BOOK)
// MACRO (CD, CD)
// MACRO (Calculator, CALCULATOR)
// MACRO (ToDoList, TODOLIST)
// MACRO (ClearGrab, CLEARGRAB)
// MACRO (Close, CLOSE)
// MACRO (Copy, COPY)
// MACRO (Cut, CUT)
// MACRO (Display, DISPLAY)
// MACRO (DOS, DOS)
// MACRO (Documents, DOCUMENTS)
// MACRO (Excel, EXCEL)
// MACRO (Explorer, EXPLORER)
// MACRO (Game, GAME)
// MACRO (Go, GO)
// MACRO (iTouch, ITOUCH)
// MACRO (LogOff, LOGOFF)
// MACRO (Market, MARKET)
// MACRO (Meeting, MEETING)
// MACRO (MenuKB, MENUKB)
// MACRO (MenuPB, MENUPB)
// MACRO (MySites, MYSITES)
// MACRO (News, NEWS)
// MACRO (OfficeHome, OFFICEHOME)
// MACRO (Option, OPTION)
// MACRO (Paste, PASTE)
// MACRO (Phone, PHONE)
// MACRO (Calendar, CALENDAR)
// MACRO (Reply, REPLY)
// MACRO (Reload, RELOAD)
// MACRO (RotateWindows, ROTATEWINDOWS)
// MACRO (RotationPB, ROTATIONPB)
// MACRO (RotationKB, ROTATIONKB)
// MACRO (Save, SAVE)
// MACRO (Send, SEND)
// MACRO (Spell, SPELL)
// MACRO (SplitScreen, SPLITSCREEN)
// MACRO (Support, SUPPORT)
// MACRO (TaskPane, TASKPANE)
// MACRO (Terminal, TERMINAL)
// MACRO (Tools, TOOLS)
// MACRO (Travel, TRAVEL)
// MACRO (Video, VIDEO)
// MACRO (Word, WORD)
// MACRO (Xfer, XFER)
// MACRO (ZoomIn, ZOOMIN)
// MACRO (ZoomOut, ZOOMOUT)
// MACRO (Away, AWAY)
// MACRO (Messenger, MESSENGER)
// MACRO (WebCam, WEBCAM)
// MACRO (MailForward, MAILFORWARD)
// MACRO (Pictures, PICTURES)
// MACRO (Music, MUSIC)
// MACRO (Battery, BATTERY)
// MACRO (Bluetooth, BLUETOOTH)
// MACRO (WLAN, WLAN)
// MACRO (UWB, UWB)
// MACRO (AudioForward, AUDIOFORWARD)
// MACRO (AudioRepeat, AUDIOREPEAT)
// MACRO (AudioRandomPlay, AUDIORANDOMPLAY)
// MACRO (Subtitle, SUBTITLE)
// MACRO (AudioCycleTrack, AUDIOCYCLETRACK)
// MACRO (Time, TIME)
// MACRO (Hibernate, HIBERNATE)
// MACRO (View, VIEW)
// MACRO (TopMenu, TOPMENU)
// MACRO (PowerDown, POWERDOWN)
// MACRO (Suspend, SUSPEND)
// MACRO (ContrastAdjust, CONTRASTADJUST)
// MACRO (TouchpadToggle, TOUCHPADTOGGLE)
// MACRO (TouchpadOn, TOUCHPADON)
// MACRO (TouchpadOff, TOUCHPADOFF)
// MACRO (MicMute, MICMUTE)
// MACRO (Red, RED)
// MACRO (Green, GREEN)
// MACRO (Yellow, YELLOW)
// MACRO (Blue, BLUE)
// MACRO (ChannelUp, CHANNELUP)
// MACRO (ChannelDown, CHANNELDOWN)
// MACRO (Guide, GUIDE)
// MACRO (Info, INFO)
// MACRO (Settings, SETTINGS)
// MACRO (MicVolumeUp, MICVOLUMEUP)
// MACRO (MicVolumeDown, MICVOLUMEDOWN)
// MACRO (New, NEW)
// MACRO (Open, OPEN)
// MACRO (Find, FIND)
// MACRO (Undo, UNDO)
// MACRO (Redo, REDO)
// MACRO (MediaLast, MEDIALAST)
// MACRO (unknown, UNKNOWN)
// MACRO (Call, CALL)
// MACRO (Camera, CAMERA)
// MACRO (CameraFocus, CAMERAFOCUS)
// MACRO (Context1, CONTEXT1)
// MACRO (Context2, CONTEXT2)
// MACRO (Context3, CONTEXT3)
// MACRO (Context4, CONTEXT4)
// MACRO (Flip, FLIP)
// MACRO (Hangup, HANGUP)
// MACRO (No, NO)
// MACRO (Select, SELECT)
// MACRO (Yes, YES)
// MACRO (ToggleCallHangup, TOGGLECALLHANGUP)
// MACRO (VoiceDial, VOICEDIAL)
// MACRO (LastNumberRedial, LASTNUMBERREDIAL)
// MACRO (Execute, EXECUTE)
// MACRO (Printer, PRINTER)
// MACRO (Play, PLAY)
// MACRO (Sleep, SLEEP)
// MACRO (Zoom, ZOOM)
// MACRO (Exit, EXIT)
// MACRO (Cancel, CANCEL)
