#include <SDL.h>


namespace djnn {

  #define SDL_EVENT_CAP_LETTER(a,A) const int SDLK_ ## A = SDLK_ ## a;

  SDL_EVENT_CAP_LETTER (a,A)
  SDL_EVENT_CAP_LETTER (b,B)
  SDL_EVENT_CAP_LETTER (c,C)
  SDL_EVENT_CAP_LETTER (d,D)
  SDL_EVENT_CAP_LETTER (e,E)
  SDL_EVENT_CAP_LETTER (f,F)
  SDL_EVENT_CAP_LETTER (g,G)
  SDL_EVENT_CAP_LETTER (h,H)
  SDL_EVENT_CAP_LETTER (i,I)
  SDL_EVENT_CAP_LETTER (j,J)
  SDL_EVENT_CAP_LETTER (k,K)
  SDL_EVENT_CAP_LETTER (l,L)
  SDL_EVENT_CAP_LETTER (m,M)
  SDL_EVENT_CAP_LETTER (n,N)
  SDL_EVENT_CAP_LETTER (o,O)
  SDL_EVENT_CAP_LETTER (p,P)
  SDL_EVENT_CAP_LETTER (q,Q)
  SDL_EVENT_CAP_LETTER (r,R)
  SDL_EVENT_CAP_LETTER (s,S)
  SDL_EVENT_CAP_LETTER (t,T)
  SDL_EVENT_CAP_LETTER (u,U)
  SDL_EVENT_CAP_LETTER (v,V)
  SDL_EVENT_CAP_LETTER (w,W)
  SDL_EVENT_CAP_LETTER (w,X)
  SDL_EVENT_CAP_LETTER (y,Y)
  SDL_EVENT_CAP_LETTER (z,Z)

  #define MACRO(lowkey,capkey) extern const int DJN_Key_ ## lowkey = SDLK_ ## capkey;
  #include "display/const_keys.h"

  #define MACRO2(lowkey,capkey,sdlkey) extern const int DJN_Key_ ## lowkey = SDLK_ ## sdlkey;
  MACRO2 (Print, PRINT, PRINTSCREEN)
  MACRO2 (Shift, SHIFT, LSHIFT)
  MACRO2 (Control, CONTROL, LCTRL)
  //MACRO2 (Meta, META, LMETA)
  MACRO2 (Alt, ALT, LALT)
  //MACRO2 (AltGr, ALTGR, LALTGR)
  MACRO2 (NumLock, NUMLOCK, NUMLOCKCLEAR)
  MACRO2 (Exclam, EXCLAM, EXCLAIM)
  MACRO2 (Apostrophe, APOSTROPHE, QUOTE)
  MACRO2 (ParenLeft, PARENLEFT, LEFTPAREN)
  MACRO2 (ParenRight, PARENRIGHT, RIGHTPAREN)
  MACRO2 (Equal, EQUAL, EQUALS)

}
